# Generated by Django 5.0.7 on 2025-11-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='about_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст о компании'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Адрес'),
        ),
    ]
