# Generated by Django 5.1.3 on 2025-11-26 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_companyinfo_about_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Ключ сессии'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(default='info@luxwood.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(default='LuxWood', max_length=200, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Ключ сессии'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Рекомендуемый'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Остаток на складе'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AddIndex(
            model_name='advantage',
            index=models.Index(fields=['is_active', 'order'], name='store_advan_is_acti_693c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['is_active', 'order'], name='store_banne_is_acti_2f31c3_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key'], name='store_cart_session_e2cd27_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='store_carti_cart_id_1ecc31_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='store_categ_slug_3348ec_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='store_categ_parent__e56892_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['-created_at'], name='store_conta_created_d4f460_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_read'], name='store_conta_is_read_16a51e_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['email'], name='store_conta_email_fb3e95_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['category', 'is_active', 'order'], name='store_faq_categor_22ac27_idx'),
        ),
        migrations.AddIndex(
            model_name='faqcategory',
            index=models.Index(fields=['order'], name='store_faqca_order_8fd98c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='store_order_created_cad692_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='store_order_status_428b25_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['email'], name='store_order_email_9efbc4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phone'], name='store_order_phone_2b6c19_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='store_order_order_i_70b6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='store_produ_slug_361302_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'featured'], name='store_produ_categor_62d187_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-rating', '-reviews_count'], name='store_produ_rating_163051_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='store_produ_created_0fbdf8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock'], name='store_produ_stock_3f6dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['product', 'order'], name='store_produ_product_6e1ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product'], name='store_produ_product_f5a1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsor',
            index=models.Index(fields=['is_active', 'order'], name='store_spons_is_acti_ec5d7f_idx'),
        ),
    ]
