# Generated by Django 5.0.7 on 2025-11-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_advantage_is_active_alter_advantage_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Главный офис, Филиал в Москве', max_length=200, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('city', models.CharField(default='Москва', max_length=100, verbose_name='Город')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('working_hours', models.CharField(default='Пн-Пт: 9:00 - 18:00', max_length=200, verbose_name='График работы')),
                ('map_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на карту')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='advantage',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-star', help_text='Примеры: fas fa-star, fas fa-shipping-fast, fas fa-shield-alt, fas fa-headset, fas fa-trophy, fas fa-gift, fas fa-clock, fas fa-check-circle', max_length=100, verbose_name='Иконка (Font Awesome класс)'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['updated_at'], name='store_cart_updated_08faa2_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_active', 'order'], name='store_conta_is_acti_cf3bff_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['city'], name='store_conta_city_6216d7_idx'),
        ),
    ]
