# Generated by Django 5.0.7 on 2025-11-30 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_all_models_multilingual'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
